### ISSUE TITLE
Mod is required to join LAN worlds if the host has the mod installed

### ISSUE THREAD

**Issue by drown3d** [S-N00B-1/consolesounds#2]
Vanilla players trying to join the LAN world of a player who has the mod installed will be kicked for something along the lines of unregistered sound events.

**Comment by S-N00B-1** [comment]
Looking into this.

**Comment by S-N00B-1** [comment]
In order to play the sound I need to register them on the client. I do not believe I can fix this issue cleanly.

**Comment by S-N00B-1** [comment]
Found a way to fix this while working on Glide stuff, will implement in next release.
